name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get etcd
      run: 'export ETCD_VER=v3.4.15 && curl -L https://github.com/etcd-io/etcd/releases/download/$ETCD_VER/etcd-$ETCD_VER-linux-amd64.tar.gz | tar xzvf - -C ~/go/bin --strip-components=1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Test with a race detector
      run: go test -race -v ./...