name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Unit Test
      run: go test -v ./...
    
    - name: Integration Test
      run: "go install -v github.com/YuriyNasretdinov/chukcha/cmd/integration-test && ~/go/bin/integration-test"
